### ISSUE TITLE
Directories from which to copy NTF and accompanying files to extra_data

### ISSUE THREAD

**Issue by mjm8** [USF-IMARS/imars_dags#72]
home1\mmccarthy\Matt\USF\Other
home1\mmccarthy\Matt\USF\test

**Comment by 7yl4r** [comment]
coming back to this and realizing I didn't put enough info here: these locations likely contain files that have been lost or may not be in `extra_data` for other reasons.

**Comment by 7yl4r** [comment]
lumped under https://github.com/USF-IMARS/issues/issues/35
