### ISSUE TITLE
s3 processing into a DAG

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/imars_dags#84]
@sebastiandig : Let's talk about getting all that s3 stuff you are doing manually onto the servers.

Look in [this directory](https://github.com/USF-IMARS/imars_dags/tree/master/dags/processing/modis_aqua_pass) and you will see a few files that may look familiarish:
* `*.xml` : the xml file passed to the l2->l3 step
* `l1_to_l2.sh` : this is similar to the `process_image.sh` script
* `*.par` : the parameter file passed into l1->l2 step
* `*.py` : this is where the airflow DAG magic lives. the important parts are:
    * [`l1_to_l2` step is defined](https://github.com/USF-IMARS/imars_dags/blob/master/dags/processing/modis_aqua_pass/modis_aqua_pass.py#L37-L75)
    * [`l3gen` step is defined](https://github.com/USF-IMARS/imars_dags/blob/master/dags/processing/modis_aqua_pass/modis_aqua_pass.py#L77-L117)
    * [airflow is told to run l2 before l3](https://github.com/USF-IMARS/imars_dags/blob/master/dags/processing/modis_aqua_pass/modis_aqua_pass.py#L119)

We can copy most of this over to set up a DAG to process S3 images automatically; it is mostly just parameters we need to change I think.
Please create a directory in [imars_dags/dags/processing](https://github.com/USF-IMARS/imars_dags/tree/master/dags/processing) and copy over the modis files linked above (or upload the S3 ones you have if that is better).

**Comment by 7yl4r** [comment]
Oops, I already had an issue open for this (https://github.com/USF-IMARS/imars_dags/issues/68). Anyway, I closed that one and we will continue here.

**Comment by sebastiandig** [comment]
@7yl4r  I've started the directory. Added the .xml files for the four locations, *l2gen.par and the process shell. The one with "_1" is only if new .xml files are added. I added modis_aqua_pass.py, but I am unsure of what needs to change between the *.py and everything else so they are compatible.

**Comment by 7yl4r** [comment]
I renamed that file & changed the `dag_name` in there to match.

I think the only other changes are : 

1. change path to xml file (currently `L3G_MODA_GOM_v2.xml`)
2. change path to par file (currently `moda_l2gen.par`)
3.  update the product ids (I will do this & update the database next week)

**Comment by sebastiandig** [comment]
Quick question regarding the [l1_to_l2.sh](https://github.com/USF-IMARS/imars_dags/blob/master/dags/processing/modis_aqua_pass/l1_to_l2.sh)
On lines from 10 -13
     ie: GEO_PATH=$TMP_DIR/geo
         OKM_PATH=$TMP_DIR/okm
         HKM_PATH=$TMP_DIR/hkm
         QKM_PATH=$TMP_DIR/qkm

I'll ask more questions as I figure out what I'm looking at.

**Comment by 7yl4r** [comment]
`$TMP_DIR` is a [bash variable](http://tldp.org/HOWTO/Bash-Prog-Intro-HOWTO-5.html). 

`geo`, `okm`, `hkm`, `qkm` are filenames. I probably should have given them file extensions but I don't remember what type of files they are.

So these lines are creating new bash variables that have the full path to the files in them. `TMP_DIR` is usually something like `/srv/imars-objects/airflow-tmp/myDAGName_mytask_20180919190021` so `QKM_PATH=$TMP_DIR/qkm` will set `QKM_PATH` to something like `/srv/imars-objects/airflow-tmp/myDAGName_mytask_20180919190021/qkm`.

**Comment by 7yl4r** [comment]
closing this since much has changed. Will re-open or open a new issue as needed.
