### ISSUE TITLE
update bouy data location

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/imars_dags#99]
The bouy data ingest task needs to be updated:

from Dan:

> The buoy data (FKNMS and FWC only) is now being generated in two locations:
> Old: /srv/imars-objects/modis_aqua_fk/SAL_TS_NDBC
> New: /srv/imars-objects/fk/SAL_TS_NDBC/
> 
> There are identical files in each location and both are updated nightly. My goal is to get rid of the "modis_aqua_fk" directory at some point. For now, either one will work, so we can leave this alone for now.

**Comment by dotis** [comment]
That's fine. It is currently generating .csv files in both old and new locations.
